src/components/events/views.py
from flask import Blueprint, render_template,request
from src import db
from datetime import datetime
from flask import Flask, render_template, flash, redirect, url_for,request, flash

# from flask_login import UserMixin, LoginManager,login_user,logout_user, current_user, login_required
# from flask import request
# from flask import session
# from DateTime import DateTime




events_blueprint=Blueprint('events',__name__,template_folder='../../templates/events')


from src.components.events.forms import AddEventForm
from src.models.user import User
from src.models.event import Event
from src.models.venue import Venue
from src.models.type import Type
from flask_login import UserMixin, LoginManager,login_user,logout_user, current_user, login_required
from werkzeug.security import generate_password_hash, check_password_hash
from src.components.account.form import LoginForm
# @events_blueprint.route('/')

# def hello():
#     form=AddEventForm()
    
#     return render_template('events.html',form=form) 

@events_blueprint.route('/add',methods=['POST','GET'])

def add():
    if not current_user.is_authenticated:
        flash("Please login")
        return redirect (url_for('account.login'))
    
    form=AddEventForm()
    datetime1 = datetime.strptime("2019-04-25 22:37",'%Y-%m-%d %H:%M' )
    form.eventtype.choices=[(t.id,t.event_type) for t in Type.query.all()]
    if request.method == 'POST':
        v=Venue(venuename=form.venue.data,locationaddress=form.location.data)
        
        
        # db.session.bulk_save_objects(multi)
        db.session.add(v)
      
        db.session.commit()

        print('*******', current_user.id)
        e=Event(title=form.title.data,description=form.description.data,organizer_id=current_user.id,venue_id=v.id,eventtype_id=form.eventtype.data,end_time=datetime1, start_time=datetime1,img_link=form.imglink.data,event_owner=form.eventowner.data)
        
        db.session.add(e)
        db.session.commit()
        flash('Successfully added')
    return render_template('add_event.html',form=form)  

@events_blueprint.route('/',methods=['POST','GET'])
def list():
    form = LoginForm()
    events = Event.query.all()
    return render_template('events.html',form=form, events = events, event_count=len(events))

src/templates/email.html
<h3 style="color: blue">Reset password</h3>
<a href="http://localhost:5000/new_password/{{token}}">Click here!</a> to set new password

src/templates/home.html
{% extends "layout.html" %} 

{% block content %}

<div class="nav-img">
  <header>
    <div class="container">
      <div class="row pt-3">
        <div class="logo col-lg-3 col-md-3 col-sm-6 col-xs-6">
          <img class="img-responsive" src="../static/logo.png" alt="image" />
          <span class=" ml-3 text-white">EVENTS COMMUNITY</span>
        </div>
        <div class="col-lg-9 col-md-9 col-sm-6 col-xs-6">
          <nav class="navbar navbar-expand-lg">
            <button
              class="navbar-toggler"
              type="button"
              data-toggle="collapse"
              data-target="#navbarTogglerDemo01"
              aria-controls="navbarTogglerDemo01"
              aria-expanded="false"
              aria-label="Toggle navigation"
            >
              <span class="text-white">
                Navigation <i class="fas fa-bars"></i
              ></span>
            </button>
            <div class="collapse navbar-collapse " id="navbarTogglerDemo01">
              <ul class="nav nav-pills mainnav ">
                <li class="nav-item dropdown">
                  <a
                    class="nav-link dropdown-toggle"
                    data-toggle="dropdown"
                    href="#"
                    role="button"
                    aria-haspopup="true"
                    aria-expanded="false"
                    >MENU</a
                  >
                  <div class="dropdown-menu">
                    <a class="dropdown-item" href="#">PRICING</a>
                    <a class="dropdown-item" href="#">SPONSOR</a>
                    <a class="dropdown-item" href="#">CONTACT US</a>
                   

                  </div>
                </li>
                <li class="nav-item dropdown">
                  <a
                    class="nav-link dropdown-toggle"
                    data-toggle="dropdown"
                    href="#"
                    role="button"
                    aria-haspopup="true"
                    aria-expanded="false"
                    >NEWS</a
                  >
                  <div class="dropdown-menu">
                    <a class="dropdown-item" href="#">Recently Added</a>
                    <a class="dropdown-item" href="#">Most Viewed</a>
                    <a class="dropdown-item" href="#">Highlights</a>
                    <div class="dropdown-divider"></div>
                    <form class="form-inline my-2 my-lg-0">
                      <input
                        class="form-control mr-sm-2"
                        type="search"
                        placeholder="Search"
                        aria-label="Search"
                      />
                    </form>
                  </div>
                </li>

                <li class="nav-item">
                  <a class="nav-link" href="#">GALLERY</a>
                </li>

                <li class="nav-item">
                  <a class="nav-link" href="{{ url_for('events.list') }}">EVENTS</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link btn-create font-weight-bold" href="{{ url_for('events.add') }}" >
                        CREATE EVENTS</a>
                </li>
                {% if current_user.is_authenticated %}
                <li class="nav-item">
                  <a class="nav-link"
                    href="{{ url_for('account.logout') }}">
                    <button
                    class="btn-sign font-weight-bold"
                    data-toggle="modal"
                    data-target="#exampleModalLong"
                  >
                    LOGOUT
                    </button>
                  </a>
                </li>
                {% else %}
                <!-- <li><a href="{{url_for('account.login')}}">Login <span class="sr-only">(current)</span></a></li> -->
                <li class="nav-item">
                  <button
                    type="button"
                    class="btn-sign font-weight-bold"
                    data-toggle="modal"
                    data-target="#exampleModalLong"
                  >
                    LOGIN
                  </button>

                  <!-- Modal -->
                  <div
                    class="modal fade"
                    id="exampleModalLong"
                    tabindex="-1"
                    role="dialog"
                    aria-labelledby="exampleModalLongTitle"
                    aria-hidden="true"
                  >
                    <div class="modal-dialog" role="document">
                      <div class="modal-content">
                        <div class="modal-body">
                          <form class="border-input" method="POST">
                            <div class="form-group font-weight-bold">
                              {{ form.email.label }}
                              <div class="input-wrapper">
                                <!-- <input class="form-control spacing" type="text"
                                                                                placeholder="Please input Event Title"> -->
                                <div class="form-control spacing  mb-2">
                                  {{ form.email() }}
                                </div>
                                <label
                                  for="stuff"
                                  class="fas fa-envelope input-icon"
                                ></label>
                              </div>
                              {{ form.password_hash.label }}
                              <div class="input-wrapper">
                                <!-- <input class="form-control spacing my-2" type="text"
                                                                                placeholder="Please input Event Venue">
                                                                            <label for="stuff" class="fas fa-building input-icon"></label> -->
                                <div class="form-control spacing">
                                  {{ form.password_hash() }}
                                </div>

                                <label
                                  for="stuff"
                                  class="fas fa-lock input-icon"
                                ></label>
                              </div>
                            </div>
                            <a href="{{ url_for('account.add') }}">
                              "Sign Up here if you don't have account yet"
                            </a>
                            
                              <p><a href="{{ url_for('account.reset') }}">
                                "Reset Password if forgot password"</a></p>
                        
                            <div class="modal-footer text-center">
                              {{ form.submit() }}
                            </div>
                          </form>
                        </div>
                      </div>
                    </div>
                  </div>
                </li>
                {% endif %}
                
              </ul>
            </div>
          </nav>
        </div>
      </div>
    </div>
  </header>
  <div class="container text-center text-white mt-5">
    <h3>FIND YOUR FARVORITE EVENTS HERE</h3>
    <div class="wrap">
      <div class="search">
        <input
          type="text"
          class="searchTerm"
          placeholder="What are you looking for?"
        />
        <button type="submit" class="searchButton">
          <i class="fa fa-search"></i>
        </button>
      </div>
    </div>
  </div>
  <div class="container  mt-5">
      <div class="row">
        <div class="col-3">
        <div class="form-group">
          <select class="custom-select" required>
            <option value="">All Location</option>
            <option value="1">One</option>
            <option value="2">Two</option>
            <option value="3">Three</option>
          </select>
          <div class="invalid-feedback">Example invalid custom select feedback</div>
        </div>
        </div>
        <div class="col-3">
          <div class="form-group">
            <select class="custom-select" required>
              <option value="">All Event Type</option>
              <option value="1">One</option>
              <option value="2">Two</option>
              <option value="3">Three</option>
            </select>
            <div class="invalid-feedback">Example invalid custom select feedback</div>
          </div>
        </div>
        <div class="col-3">
          <div class="form-group">
            <select class="custom-select" required>
              <option value="">All Date</option>
              <option value="1">One</option>
              <option value="2">Two</option>
              <option value="3">Three</option>
            </select>
            <div class="invalid-feedback">Example invalid custom select feedback</div>
          </div>
        </div>
        <div class="col-3">
          <div class="form-group">
            <select class="custom-select" required>
              <option value="">All Price</option>
              <option value="1">One</option>
              <option value="2">Two</option>
              <option value="3">Three</option>
            </select>
            <div class="invalid-feedback">Example invalid custom select feedback</div>
          </div>
        </div>
      </div>
      </div>
</div>


{% endblock %}

src/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Events Community</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{{ url_for('static', filename='main.css') }}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"
        integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css"
    href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.1/css/bootstrap-datepicker3.min.css">
<link rel="icon" type="image/png" href="../static/logo.png">
    </head>
<body>
    <div class="container">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
        {%for message in messages %}
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            <strong>{{message}}</strong>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    
        {% endfor %}
        {% endif %}
        {% endwith %}
    </div>
    
    
    {% block content %}
    {% endblock %}

    
   
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
    crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
    crossorigin="anonymous"></script>
    <script type="text/javascript"
        src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/js/bootstrap-datepicker.min.js"></script>
</body>
</html>

src/templates/new_password.html
<form method="POST">
    {{ form.hidden_tag() }}
    <div class="form-group">
        <label for="password"> {{  form.password.label }}</label>
        {{  form.password() }}
        {% for error in  form.password.errors %}
        <span style="color: red;">{{ error }}</span>
        {% endfor %}
    </div>
    <div class="form-group">
        <label for="confirm"> {{  form.confirm.label }}</label>
        {{  form.confirm() }}
        {% for error in  form.confirm.errors %}
        <span style="color: red;">{{ error }}</span>
        {% endfor %}
    </div>
    <div class="form-group">
        {{ form.submit() }}
    </div>
</form>

src/templates/reset.html
<form method="POST">
    {{ form.hidden_tag() }}
    <div class="form-group">
        <label for="email"> {{  form.email.label }}</label>
        {{  form.email() }}
        {% for error in  form.email.errors %}
        <span style="color: red;">{{ error }}</span>
        {% endfor %}
    </div>
    <div class="form-group">
        {{ form.submit() }}
    </div>
</form>

src/templates/signup.html
{% extends "layout.html" %}
{% block content %}
{{ form.hidden_tag() }}
<h3>Signup</h3>
<div class="add-event-bg">
    <form class="" method="POST">

<p>
{{ form.username.label }}
    {{ form.username() }}
</p>
<p>
{{ form.email.label}}
{{ form.email() }}
</p>

<p>
    {{ form.phonenumber.label}}
    {{ form.phonenumber() }}
</p>
<p>
    {{ form.password_hash.label}}
    {{ form.password_hash() }}
</p>

{{form.submit}}
{% endblock %}